### PR TITLE
Markdown: show answer, display for clue references too

### LINKED ISSUE #159: Reference tooltip in comments
E.g. '29-Across' should get a tooltip, same as it does in a clue

### PR DESCRIPTION
**Pull request by glasser**
As far as I can tell, `<Markdown clueMap=...>` is only used in post-solve
comments so it should be OK to include the answer in the tooltip.

This implementation only supports `\d+[AD]` references; it could be generalized
later to support other ways of referring to clues.

Fixes #159.

### CODE REVIEW

**Comment by glasser** [comment]
I don't think these test failures are related to my change. When running locally I see some similar failures which succeed when I rerun failed tests.

**Comment by mdirolf** [comment]
Yeah the intermittent failures on travis are quite annoying. I've got this issue open https://github.com/mdirolf/crosshare/issues/252 to try to figure them out - unfortunately I never see them locally so it's hard to debug.

I will pull this locally and give it a run but from a quick glance it looks really nicely done! I like the way you added the "5A" strings to the map rather than mucking around w/ a new regex - very clever.

Do you think it's worth trying to support `5-A` and `5-Across` as well? Most folks probably tend towards 5A I think, so maybe not worth it. `5-Across` would be particularly annoying w/ this implementation as we'd have to add different possible capitalization of Across

**Comment by glasser** [comment]
Sure, I'll add the 2x3 grid of A vs Across, no space, space, dash, and not stress too much about about arbitrary spacing and capitalization?

**Comment by mdirolf** [comment]
Sounds great except I think I'd leave off the space options - might be more likely to false positive. Maybe just 5A, 5-A and 5-Across for each?

**Comment by glasser** [comment]
OK, done!

Out of curiosity, does this get auto-deployed to crosshare.org after merge?

**Comment by mdirolf** [comment]
Awesome, thanks! I'm going to take a closer look at it and merge shortly :). It doesn't get auto-deployed. There isn't a great process in place yet for timing deploys, to date it has mostly happened whenever I feel like it. The goal is definitely to keep the master branch in a "deployable" state, though. I added a "awaiting deployment" tag that can get added to issues once they're fixed in master and then they can get closed when actually deployed.

Open to any suggestions for that process, though!

**Pull request merged**
