### PR TITLE
Rework keypress handling

### LINKED ISSUE #353: Some keyboard shortcuts are ignored
When crossword is active (in editor or not paused or not completed), certain keyboard inputs like F5 (refresh) or F11 (fullscreen) are ignored. Perhaps unrecognized inputs should just do their normal action?

### PR DESCRIPTION
**Pull request by 1Computer1**
- Adds type & enum for keypresses
- No longer eats up unrecognized inputs

I skipped figuring out those builder hotkeys for now :P  
Also, should there be more allowed characters? Maybe `/^[\pL\pN]$/`?

Fixes #353

### CODE REVIEW

**Comment by mdirolf** [comment]
I still need to take a closer look, but on first blush this looks awesome! Thank you! I'm glad you used some of the fp-ts stuff - I've been meaning to invest some time in learning that lib but so far have only used the io-ts portion for runtime type checking from the db.

What do you mean by "skipped figuring out those builder hotkeys for now"?

As for more allowed characters - I think there should be. My main hesitation is that it necessitates changing the mobile/soft keyboard to find a way for folks to enter them. I think for now let's just stick on adding support for characters as needed/requested (like Ñ that recently got added), unless you have a good idea for supporting them in the keyboard.

**Comment by mdirolf** [comment]
The only thing I'd like to change before merging is to change `Tilde` to `Backtick` throughout - I think ~ is tilde and ` is usually called a backtick. LMK if you're able to add that or else I can merge and then edit it afterwards. Thanks again!

**Comment by 1Computer1** [comment]
Whoops! I knew that but wrote Tilde anyways lol

**Comment by mdirolf** [comment]
Just realized this is swallowing browser shortcuts like ctrl-r - oops! We need to change that back before deploying this

**Comment by mdirolf** [comment]
Fixed the above in 68bc62aa2af2aed2523bb14858758b9dab5efe75

**Pull request merged**
