### PR TITLE
Link to another site for suggestions

### PR DESCRIPTION
**Pull request by 1Computer1**
I find myself tabbing out to these places a lot, so why not just embed them into the suggestion overlay :P
Not very good at styling, it feels kinda jank atm.
Any other sites that should be added?

### CODE REVIEW

**Comment by mdirolf** [comment]
Thanks for the PR! I think the idea is quite clever. For a couple of reasons (the main one is styling), I don't want to embed whole pages like this that aren't designed to be embedded. 

I think the cleanest way to add this type of thing would be if any of these sources offer API access. Then we could style the results however we like, ensure they are useable on mobile, etc. Alternatively, if they offer a widget designed to be embedded we could try to make that work.

**Comment by 1Computer1** [comment]
New change makes it only links, for several reasons iframes aren't great here. Unfortunately pretty much all the sources don't provide a good way for us to get their data.

**Comment by mdirolf** [comment]
This change looks good! Do you have any confirmation that wordnerd is open source? I saw the GH account you linked but wasn't able to find any repo for it. It's not the end of the world but I would feel better linking out to a site that I knew was an open effort (like wikipedia and wiktionary)

**Comment by mdirolf** [comment]
Merged, thanks @1Computer1!

**Pull request merged**
